name    'jbussdieker-graphite_web'
version '0.0.1'
source 'http://github.com/jbussdieker/puppet-graphite_web'
author 'Joshua Bussdieker'
license 'MIT'
summary 'Puppet Graphite management module'
description 'This module can be used for basic Graphite management'
project_page 'http://github.com/jbussdieker/puppet-graphite_web'

dependency 'jbussdieker/whisper'
